name: Build Windows .exe

on:
  push:
    branches: [main]
  workflow_dispatch: # allows manual trigger from GitHub UI

jobs:
  build:
    name: Build Windows App
    runs-on: windows-latest
    outputs:
      tag_name: ${{ steps.set_tag.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop
        shell: bash

      - name: Install dependencies
        run: flutter pub get
        shell: bash

      - name: Build Windows executable
        run: flutter build windows
        shell: bash

      - name: Upload Release folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: build/windows/x64/runner/Release

      - name: Set tag name
        id: set_tag
        run: echo "tag=v1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT
        shell: bash

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-exe
          path: windows-build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.build.outputs.tag_name }}
          name: Windows Release ${{ needs.build.outputs.tag_name }}
          files: windows-build/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
