name: Flutter Android Build and Release (armeabi-v7a Debug)

on:
  push:
    tags:
      - 'v*'  # Trigger on semantic version tags
  workflow_dispatch:

permissions:
  contents: write  # Required for creating releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for tag information
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          
      - name: Install Flutter dependencies
        run: flutter pub get
        
      - name: Check Flutter doctor
        run: flutter doctor -v
        
      - name: Build Debug APK (armeabi-v7a)
        run: flutter build apk --debug --target-platform android-arm  # Forces armeabi-v7a build
        
      - name: Prepare APK files
        run: |
          mv build/app/outputs/flutter-apk/app-debug.apk app-armeabi-v7a-debug.apk  # Rename to indicate architecture
          cp app-armeabi-v7a-debug.apk app-${{ github.ref_name }}-armeabi-v7a-debug.apk
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app-armeabi-v7a-debug.apk
            app-${{ github.ref_name }}-armeabi-v7a-debug.apk
          tag_name: ${{ github.ref_name }}
          name: Debug Release (armeabi-v7a) ${{ github.ref_name }}
          body: |
            ### Debug Release Notes (armeabi-v7a)
            - Version: ${{ github.ref_name }}
            - Architecture: armeabi-v7a (for older Android devices)
            - Build Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
            - Build Type: Debug
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}