name: Flutter Android Build and Release (Debug)

on:
  push:
    tags:
      - 'v*'  # Trigger on semantic version tags
  workflow_dispatch:

permissions:
  contents: write  # Required for creating releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for tag information
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          
      - name: Install Flutter dependencies
        run: flutter pub get
        
      - name: Check Flutter doctor
        run: flutter doctor -v
        
      - name: Build Debug APK
        run: flutter build apk --debug  # Changed from --release to --debug
        
      - name: Prepare APK files
        run: |
          mv build/app/outputs/flutter-apk/app-debug.apk app-latest-debug.apk  # Changed filename
          cp app-latest-debug.apk app-${{ github.ref_name }}-debug.apk  # Added -debug suffix
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app-latest-debug.apk
            app-${{ github.ref_name }}-debug.apk
          tag_name: ${{ github.ref_name }}
          name: Debug Release ${{ github.ref_name }}  # Added Debug prefix
          body: |
            ### Debug Release Notes
            - Version: ${{ github.ref_name }}
            - Build Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
            - Build Type: Debug
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}