name: Flutter Android Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on semantic version tags (v1.0.0, v2.1.3, etc.)
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          
      - name: Install Flutter dependencies
        run: flutter pub get
        
      - name: Check Flutter doctor
        run: flutter doctor -v
        
      - name: Build APK
        run: flutter build apk --release
        
      - name: Rename APK to consistent name
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk \
             build/app/outputs/flutter-apk/app-latest.apk
          cp build/app/outputs/flutter-apk/app-latest.apk \
             build/app/outputs/flutter-apk/app-${{ github.ref_name }}.apk
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/app-latest.apk
            build/app/outputs/flutter-apk/app-${{ github.ref_name }}.apk
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ### Release Notes
            - Version: ${{ github.ref_name }}
            - Build Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
            - [View Changelog](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md)
          draft: false
          prerelease: false